"""
Export tab — GIS file summary + open output folder.
"""
import os
import glob
import subprocess
import platform

from PyQt6.QtWidgets import (
    QWidget, QHBoxLayout, QVBoxLayout, QLabel, QGroupBox, QTableWidget,
    QTableWidgetItem, QTabWidget
)
from PyQt6.QtCore import Qt

from rivsat.app.state import state
from rivsat.app.qt.theme import COLORS, pill
from rivsat.app.qt.common import StepHeader, make_button


class ExportTab(QWidget):
    def __init__(self):
        super().__init__()
        self._build()
        self.refresh()

    def _build(self):
        root = QHBoxLayout(self)
        root.setContentsMargins(12, 12, 12, 12); root.setSpacing(10)

        panel = QWidget(); panel.setFixedWidth(270)
        pl = QVBoxLayout(panel); pl.setContentsMargins(0, 0, 0, 0); pl.setSpacing(8)
        pl.addWidget(StepHeader(6, "GIS Export & Summary"))
        desc = QLabel("All GeoTIFF rasters, CSV time-series, and PNG figures "
                      "generated by RivSat. Load GeoTIFFs directly into QGIS or ArcGIS Pro.")
        desc.setWordWrap(True); desc.setStyleSheet(f"color:{COLORS['muted']};font-size:11px;")
        pl.addWidget(desc)

        btns = QHBoxLayout()
        self.refresh_btn = make_button("↺  Refresh")
        self.open_btn    = make_button("📁  Open Folder", accent="primary")
        self.refresh_btn.clicked.connect(self.refresh)
        self.open_btn.clicked.connect(self._open_folder)
        btns.addWidget(self.refresh_btn); btns.addWidget(self.open_btn)
        bw = QWidget(); bw.setLayout(btns)
        pl.addWidget(bw)

        self.summary = QLabel(""); self.summary.setTextFormat(Qt.TextFormat.RichText)
        self.summary.setWordWrap(True)
        sg = QGroupBox("Session Summary")
        sgl = QVBoxLayout(sg); sgl.addWidget(self.summary)
        pl.addWidget(sg)

        self.status = QLabel(""); self.status.setTextFormat(Qt.TextFormat.RichText)
        pl.addWidget(self.status)
        pl.addStretch(1)
        root.addWidget(panel)

        # Right — tabbed file tables
        self.tabs = QTabWidget()
        self.tif_tbl = self._make_table(["GeoTIFF Raster", "Size KB"])
        self.csv_tbl = self._make_table(["CSV File", "Size KB"])
        self.png_tbl = self._make_table(["PNG Figure", "Size KB"])
        self.tabs.addTab(self.tif_tbl, "🗺  GeoTIFFs")
        self.tabs.addTab(self.csv_tbl, "📊  CSVs")
        self.tabs.addTab(self.png_tbl, "🖼  Figures")
        root.addWidget(self.tabs, stretch=1)

    def _make_table(self, headers):
        t = QTableWidget(0, len(headers))
        t.setHorizontalHeaderLabels(headers)
        t.horizontalHeader().setStretchLastSection(True)
        t.verticalHeader().setVisible(False)
        return t

    def _fill(self, table, files):
        table.setRowCount(len(files))
        for r, f in enumerate(files):
            table.setItem(r, 0, QTableWidgetItem(os.path.basename(f)))
            kb = os.path.getsize(f) // 1024
            table.setItem(r, 1, QTableWidgetItem(f"{kb:,}"))

    def refresh(self):
        out = os.path.abspath(state.output_dir)
        tifs = sorted(set(glob.glob(f"{out}/rasters/*.tif") + glob.glob(f"{out}/**/*.tif", recursive=True)))
        csvs = sorted(glob.glob(f"{out}/*.csv"))
        pngs = sorted(glob.glob(f"{out}/*.png"))
        self._fill(self.tif_tbl, tifs)
        self._fill(self.csv_tbl, csvs)
        self._fill(self.png_tbl, pngs)
        self.tabs.setTabText(0, f"🗺  GeoTIFFs ({len(tifs)})")
        self.tabs.setTabText(1, f"📊  CSVs ({len(csvs)})")
        self.tabs.setTabText(2, f"🖼  Figures ({len(pngs)})")

        rows = [
            ("📍 Site", state.site_name),
            ("🛰 Scenes acquired", str(len(state.scene_dirs))),
            ("⚗ Scenes processed", str(len(state.processed_results))),
            ("📄 GeoTIFFs", str(len(tifs))),
            ("📊 CSVs", str(len(csvs))),
            ("🖼 PNGs", str(len(pngs))),
        ]
        html = "".join(
            f'<div style="display:flex;justify-content:space-between;padding:3px 0;'
            f'border-bottom:1px solid #eef0f4;font-size:11px;">'
            f'<span>{k}</span><span style="font-weight:600;color:{COLORS["navy"]};">{v}</span></div>'
            for k, v in rows
        )
        html += (f'<div style="margin-top:6px;font-size:10px;color:{COLORS["muted"]};">'
                 f'📂 {out}</div>')
        self.summary.setText(html)
        self.status.setText(pill(f"✔ {len(tifs)} rasters · {len(csvs)} CSVs", "green"))

    def _open_folder(self):
        path = os.path.abspath(state.output_dir)
        try:
            os.makedirs(path, exist_ok=True)
            if platform.system() == "Windows":
                os.startfile(path)
            elif platform.system() == "Darwin":
                subprocess.Popen(["open", path])
            else:
                subprocess.Popen(["xdg-open", path])
        except Exception as exc:  # noqa: BLE001
            self.status.setText(pill(f"✗ {exc}", "red"))
